os: linux

language: elixir

env:
  TOXIPROXY_VERSION="2.1.3"

jobs:
  - elixir: 1.5
    otp_release: 19.3
  - elixir: 1.6
    otp_release: 20.3
  - elixir: 1.9.4
    otp_release: 20.3.8
  - elixir: 1.10.4
    otp_release: 21.3.8
  - elixir: 1.10.4
    otp_release: 23.0.3

services:
  - redis-server

before_install:
  - curl -L "https://github.com/Shopify/toxiproxy/releases/download/v${TOXIPROXY_VERSION}/toxiproxy_${TOXIPROXY_VERSION}_amd64.deb" > toxiproxy.deb
  - sudo dpkg -i toxiproxy.deb

before_script:
  - cd sidekiq && bundle install && cd ..
  - toxiproxy-server > /dev/null &
  - redis-server config/sentinel_config.conf --sentinel
  - sleep 4
  - toxiproxy-cli create redis -l localhost:26379 -u localhost:6379
  - sleep 1

script:
  - mix compile --warnings-as-errors
  - "! mix help format > /dev/null || mix format --check-formatted"
  - mix test --include integration --trace
