os: linux

language: elixir

env:
  TOXIPROXY_VERSION:2.1.3

elixir:
  - 1.5.2
  - 1.5.3
  - 1.6.0

otp_release:
  - 19.0
  - 20.2

services:
  - redis-server

before_install:
  - uname -a 
  - curl -L https://github.com/Shopify/toxiproxy/releases/download/v${TOXIPROXY_VERSION}/toxiproxy-server-linux-amd64 > ~/toxiproxy-server
  - chmod +x ~/toxiproxy-server
  - curl -L https://github.com/Shopify/toxiproxy/releases/download/v${TOXIPROXY_VERSION}/toxiproxy-cli-linux-amd64 > ~/toxiproxy-cli
  - chmod +x ~/toxiproxy-cli

before_script:
  - cd sidekiq && bundle install && cd ..
  - ~/toxiproxy-server &
  - sleep 4
  - ~/toxiproxy-cli create redis -l localhost:26379 -u localhost:6379
  - sleep 1
